package com.extremityIndia.model;



/**
 * Login generated by MyEclipse - Hibernate Tools
 */

public class Login  implements java.io.Serializable {


    // Fields    

     private String email;
     private String pass;


    // Constructors

    /** default constructor */
    public Login() {
    }

    
    /** full constructor */
    public Login(String email, String pass) {
        this.email = email;
        this.pass = pass;
    }

   
    // Property accessors

    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
   








}