package com.extremityIndia.hibernate;



/**
 * Systemlogin generated by MyEclipse - Hibernate Tools
 */

public class Systemlogin  implements java.io.Serializable {


    // Fields    

     private Integer uid;
     private String uname;
     private String password;
     private String utype;
     private Integer regid;


    // Constructors

    /** default constructor */
    public Systemlogin() {
    }

    
    /** full constructor */
    public Systemlogin(Integer uid, String uname, String password, String utype, Integer regid) {
        this.uid = uid;
        this.uname = uname;
        this.password = password;
        this.utype = utype;
        this.regid = regid;
    }

   
    // Property accessors

    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }

    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    public String getUtype() {
        return this.utype;
    }
    
    public void setUtype(String utype) {
        this.utype = utype;
    }

    public Integer getRegid() {
        return this.regid;
    }
    
    public void setRegid(Integer regid) {
        this.regid = regid;
    }
   








}